# Generated by Django 2.1.7 on 2019-02-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overrideuser', '0002_auto_20190228_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
